import React, { useEffect, useState } from "react";
import axios from "axios";
import {
  BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  LineChart, Line
} from "recharts";
import { Briefcase, Users, CheckCircle, Clock, Download, FileText } from "lucide-react";

const Analytics = () => {
  const BACKEND_URL = import.meta.env.VITE_API_URL || "http://localhost:5001";
  
  const [stats, setStats] = useState({
    jobs: 0,
    applications: 0,
    pending: 0,
    accepted: 0,
    rejected: 0,
    courses: 0
  });

  const getAuthConfig = () => {
    let token = localStorage.getItem("token");
    if (!token) {
        const userInfo = localStorage.getItem("userInfo");
        if (userInfo) token = JSON.parse(userInfo).token;
    }
    return { headers: { Authorization: `Bearer ${token}` }, withCredentials: true };
  };

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [jobsRes, appsRes] = await Promise.all([
          axios.get(`${BACKEND_URL}/api/jobs`, getAuthConfig()),
          axios.get(`${BACKEND_URL}/api/applications/hr`, getAuthConfig())
        ]);

        const myJobs = jobsRes.data.data || [];
        const myApps = appsRes.data || [];
        const courses = JSON.parse(localStorage.getItem("hr_courses") || "[]");

        setStats({
          jobs: myJobs.length,
          applications: myApps.length,
          pending: myApps.filter(a => a.status === "Pending").length, 
          accepted: myApps.filter(a => a.status === "Accepted").length,
          rejected: myApps.filter(a => a.status === "Rejected").length,
          courses: courses.length
        });

      } catch (err) {
        console.error("Error loading analytics", err);
      }
    };

    fetchData();
  }, []);

 
  const handleExportCSV = () => {
    const csvContent = 
      `Metric,Count\n` +
      `Total Applications Received,${stats.applications}\n` +
      `Jobs Posted,${stats.jobs}\n` +
      `Pending Reviews,${stats.pending}\n` +
      `Candidates Accepted,${stats.accepted}\n` +
      `Candidates Rejected,${stats.rejected}\n` +
      `Active Courses,${stats.courses}\n` +
      `\nGenerated by CareerKarma HR Portal`;

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "HR_Analytics_Report.csv";
    link.click();
  };

  
  const handleExportPDF = () => {
    window.print();
  };

  
  const enrollmentData = [
    { name: 'Jan', value: 400 },
    { name: 'Feb', value: 300 },
    { name: 'Mar', value: 550 },
    { name: 'Apr', value: 450 },
    { name: 'May', value: stats.courses * 150 + 100 }, 
    { name: 'Jun', value: stats.courses * 200 + 50 },
  ];

  const hiringData = [
    { name: 'Total Received', value: stats.applications }, 
    { name: 'Pending', value: stats.pending },
    { name: 'Accepted', value: stats.accepted },
    { name: 'Rejected', value: stats.rejected }
  ];

  return (
    <div className="p-8 bg-gray-50 min-h-screen font-sans print:bg-white print:p-0">
      
      {/* HEADER & ACTIONS */}
      <div className="flex flex-col md:flex-row justify-between items-center mb-8 print:hidden">
        <h1 className="text-3xl font-bold text-gray-800">Analytics Overview</h1>
        <div className="flex gap-3 mt-4 md:mt-0">
            <button 
                onClick={handleExportCSV}
                className="flex items-center gap-2 bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-700 transition shadow-sm"
            >
                <FileText size={18} /> Export Excel
            </button>
            <button 
                onClick={handleExportPDF}
                className="flex items-center gap-2 bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-700 transition shadow-sm"
            >
                <Download size={18} /> Save as PDF
            </button>
        </div>
      </div>

      {/* Title visible only on Print */}
      <div className="hidden print:block mb-6 text-center">
          <h1 className="text-2xl font-bold">CareerKarma - HR Report</h1>
          <p className="text-gray-500">{new Date().toLocaleDateString()}</p>
      </div>

      {/* TOP CARDS */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        
        {/* Total Applications */}
        <div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-indigo-500 print:border">
          <div className="flex justify-between items-center">
            <div>
              <p className="text-sm text-gray-500 mb-1">Total Applications Received</p>
              <h3 className="text-3xl font-bold text-gray-800">{stats.applications}</h3>
            </div>
            <div className="p-3 bg-indigo-50 rounded-full text-indigo-600 print:hidden"><Users /></div>
          </div>
        </div>

        {/* Pending Review */}
        <div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-yellow-500 print:border">
          <div className="flex justify-between items-center">
            <div>
              <p className="text-sm text-gray-500 mb-1">Pending Review</p>
              <h3 className="text-3xl font-bold text-gray-800">{stats.pending}</h3>
            </div>
            <div className="p-3 bg-yellow-50 rounded-full text-yellow-600 print:hidden"><Clock /></div>
          </div>
        </div>

        {/* Jobs Posted */}
        <div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-green-500 print:border">
          <div className="flex justify-between items-center">
            <div>
              <p className="text-sm text-gray-500 mb-1">Jobs Posted</p>
              <h3 className="text-3xl font-bold text-gray-800">{stats.jobs}</h3>
            </div>
            <div className="p-3 bg-green-50 rounded-full text-green-600 print:hidden"><Briefcase /></div>
          </div>
        </div>

        {/* Acceptance Rate */}
        <div className="bg-white p-6 rounded-xl shadow-sm border-l-4 border-purple-500 print:border">
          <div className="flex justify-between items-center">
            <div>
              <p className="text-sm text-gray-500 mb-1">Acceptance Rate</p>
              <h3 className="text-3xl font-bold text-gray-800">
                {stats.applications > 0 ? Math.round((stats.accepted / stats.applications) * 100) : 0}%
              </h3>
            </div>
            <div className="p-3 bg-purple-50 rounded-full text-purple-600 print:hidden"><CheckCircle /></div>
          </div>
        </div>
      </div>

      {/* CHARTS SECTION */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* HIRING FUNNEL */}
        <div className="bg-white p-6 rounded-xl shadow-sm print:shadow-none print:border">
          <h3 className="text-xl font-bold text-gray-800 mb-6">Application Status</h3>
          <div className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={hiringData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis axisLine={false} tickLine={false} />
                <Tooltip cursor={{ fill: '#f3f4f6' }} />
                <Bar dataKey="value" fill="#4f46e5" radius={[4, 4, 0, 0]} barSize={40} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* ENROLLMENT TREND */}
        <div className="bg-white p-6 rounded-xl shadow-sm print:shadow-none print:border">
          <h3 className="text-xl font-bold text-gray-800 mb-6">Course Enrollment Trend</h3>
          <div className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={enrollmentData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} />
                <XAxis dataKey="name" axisLine={false} tickLine={false} />
                <YAxis axisLine={false} tickLine={false} />
                <Tooltip />
                <Line type="monotone" dataKey="value" stroke="#8b5cf6" strokeWidth={3} dot={{ r: 4 }} />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

      </div>
    </div>
  );
};

export default Analytics;